### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by danielchicote** [luigifab38/urlnosql#1]
Excuse my ignorance, but what are the benefits of this module over the urlrewrites?

**Comment by luigifab** [comment]
Sorry, no notification from github...

Compared to Magento products urlrewrites, no database are used.

For example, if you configure your products url like this: _id-attribute_name.html_, nothing is added in database. If you change the name of the product or the url format, again, nothing is added in database, the old url is automatically redirected to the new.

Moreover, you can share short url: id.html (the short url is automatically redirected to the "long").
